INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'jedna', 'Jenda', 'to máš jedno', 'to máš dvě', '<h1>to máš jedno</h1>', '2021-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'dve', 'Honza', 'to máš dvě', 'to máš dvě', '<h1>to máš dvě</h1>', '2021-05-02');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'tri', 'Jeník', 'to máš srovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', null);
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'ctyri', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'pet', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'sest', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'sedm', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'osm', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'devet', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'deset', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'jedenact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('dvanact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'trinact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'ctrnact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'patnact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'sesnact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'sedmnact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'osmnact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'devatenact', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'dvacet', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'dvacetjedna', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'dvacetdva', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST ( SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'dvacettri', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ( 'dvacetctyry', 'Tomáš', 'to máš urovnaný', 'to máš srovnaný', '<h1>to máš srovnaný</h1>', '2022-05-01');